###################################
# Author: Ashish Kumar Saxena
###################################

version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - ash_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: admin-backend
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./backend/src:/app/src
    networks:
      - ash_network


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: admin-frontend
    ports:
      - '8080:8080'
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - ash_network


  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - ash_network


  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./empty.conf:/etc/nginx/conf.d/default.conf:ro
      - ./admin.conf:/etc/nginx/conf.d/admin.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - ash_network

networks:
  ash_network:
